//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertimas.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertimas.Translation.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current key?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteTheCurrentKey {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheCurrentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Key.
        /// </summary>
        internal static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry count: {0} (Visible: {1}).
        /// </summary>
        internal static string EntryCount {
            get {
                return ResourceManager.GetString("EntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while saving: .
        /// </summary>
        internal static string ExceptionWhileSaving {
            get {
                return ResourceManager.GetString("ExceptionWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the folder of the project, typically where the sln file is:.
        /// </summary>
        internal static string FolderDialogDescription {
            get {
                return ResourceManager.GetString("FolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this field can not be copied..
        /// </summary>
        internal static string InThisFieldCanNotBeCopied {
            get {
                return ResourceManager.GetString("InThisFieldCanNotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected!.
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save files?.
        /// </summary>
        internal static string SaveFiles {
            get {
                return ResourceManager.GetString("SaveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is no valid language field for translation..
        /// </summary>
        internal static string ThisIsNoValidLanguageFieldForTranslation {
            get {
                return ResourceManager.GetString("ThisIsNoValidLanguageFieldForTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource file already exists!.
        /// </summary>
        internal static string ThisResourceFileAlreadyExists {
            get {
                return ResourceManager.GetString("ThisResourceFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you save your unsaved files?.
        /// </summary>
        internal static string WouldYouSaveYourUnsavedFiles {
            get {
                return ResourceManager.GetString("WouldYouSaveYourUnsavedFiles", resourceCulture);
            }
        }
    }
}
